version: '3.6'

services:
  postgres:
    restart: always
    image: postgres:latest
  web:
    build: ./server
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/docker_server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./docs
    command: "mkdocs serve"
    volumes:
      - ./docs:/docker_server
    ports:
      - "8001:8001"
    depends_on:
      - web