site_name: server
site_description: Server mamkin trader
repo_url: https://github.com/mamkin-trader/server
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/mamkin-trader">mamkin-trader</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
